import Footer from "./components/Footer"
import Navigation from "./components/Navigation"
import '../globals.css'
import Provider from "./components/Provider"

export const metadata = {
  title: 'Nikey',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <Navigation />
          {children}
          <Footer />
        </Provider>
        </body>
    </html>
  )
}
