import '../globals.css'
import Navigation from './components/Navigation'
export const metadata = {
  title: 'Admin',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
            <Navigation />
            <div className="mx-auto lg:ml-80">
                {children}
            </div>
        </body>
    </html>
  )
}
